// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTu6ucDypjELbqZYnV91sEF97V6HXrTsQ',
    appId: '1:1002072035436:web:437e761de9475cdb66c849',
    messagingSenderId: '1002072035436',
    projectId: 'quizapp-81f5b',
    authDomain: 'quizapp-81f5b.firebaseapp.com',
    storageBucket: 'quizapp-81f5b.firebasestorage.app',
    measurementId: 'G-JT9FJ730SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiRId_9TVHmIbx0dBZJ_vAsk9Ma0myXP8',
    appId: '1:1002072035436:android:70d5902edcdbb76c66c849',
    messagingSenderId: '1002072035436',
    projectId: 'quizapp-81f5b',
    storageBucket: 'quizapp-81f5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB91rf0hS2-qtSUisK8UU0nd7oIhkZJAd8',
    appId: '1:1002072035436:ios:bb1b763526500fed66c849',
    messagingSenderId: '1002072035436',
    projectId: 'quizapp-81f5b',
    storageBucket: 'quizapp-81f5b.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB91rf0hS2-qtSUisK8UU0nd7oIhkZJAd8',
    appId: '1:1002072035436:ios:bb1b763526500fed66c849',
    messagingSenderId: '1002072035436',
    projectId: 'quizapp-81f5b',
    storageBucket: 'quizapp-81f5b.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTu6ucDypjELbqZYnV91sEF97V6HXrTsQ',
    appId: '1:1002072035436:web:1c206ec90c67a7ba66c849',
    messagingSenderId: '1002072035436',
    projectId: 'quizapp-81f5b',
    authDomain: 'quizapp-81f5b.firebaseapp.com',
    storageBucket: 'quizapp-81f5b.firebasestorage.app',
    measurementId: 'G-RYW09QCS6Q',
  );
}
